[build]
  base = "docs"
  publish = "/src/.vuepress/dist"
  command = "vuepress build src/."

[[redirects]]
  from = "http://billing-docs.netlify.app/*"
  to = "https://docs.cloud.prestashop.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://billing-docs.netlify.app/*"
  to = "https://docs.cloud.prestashop.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://billing-docs.netlify.app"
  to = "https://docs.cloud.prestashop.com"
  status = 301
  force = true

[[redirects]]
  from = "https://billing-docs.netlify.app"
  to = "https://docs.cloud.prestashop.com"
  status = 301
  force = true

[[redirects]]
  from = "http://fabulous-parfait-32b8e2.netlify.app/*"
  to = "https://docs.cloud.prestashop.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://fabulous-parfait-32b8e2.netlify.app/*"
  to = "https://docs.cloud.prestashop.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://fabulous-parfait-32b8e2.netlify.app"
  to = "https://docs.cloud.prestashop.com"
  status = 301
  force = true

[[redirects]]
  from = "https://fabulous-parfait-32b8e2.netlify.app"
  to = "https://docs.cloud.prestashop.com"
  status = 301
  force = true